# Dependabot will run on day 6 of each month at 03:47 (Europe/Berlin timezone)
version: 2
updates:

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'cron'
      timezone: 'Europe/Berlin'
      cronjob: '44 2 9 * *'
    open-pull-requests-limit: 15

  - package-ecosystem: 'npm'
    directory: '/'
    cooldown:
      default: 7
    schedule:
      interval: 'cron'
      timezone: 'Europe/Berlin'
      cronjob: '44 2 9 * *'
    open-pull-requests-limit: 20
    versioning-strategy: 'increase'
    ignore:
      - dependency-name: 'typescript'
        update-types:
          - 'version-update:semver-major'
      - dependency-name: '@types/node'
        update-types:
          - 'version-update:semver-major'
